# src: https://gist.github.com/rodydavis/bde9a9a8c2fcdcf3474c0f50248f2e3a

name: Flutter Build
on: [push, pull_request]

# Cancel jobs and just run the last one
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: example/

jobs:
  build_web:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter pub get
      - run: flutter config --enable-web
      - run: flutter build web

  build_ios:
    name: Build iOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ios --release --no-codesign

  build_android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter pub get
      - run: flutter build appbundle

